create table public.publicadores_retirados (
  id uuid primary key,
  primer_apellido character varying,
  segundo_apellido character varying,
  primer_nombre character varying,
  segundo_nombre character varying,
  direccion character varying,
  codigo_municipio character varying,
  codigo_departamento character varying,
  correo_electronico character varying,
  movil character varying,
  codigo_congregacion integer,
  fecha_nacimiento date,
  sexo character varying,
  fecha_bautismo date,
  estado_civil character varying,
  nombre_conyuge character varying,
  privilegio_min character varying,
  privilegio_ser character varying,
  participo_antes character varying,
  fecha_solicitud date,
  estado character varying,
  fecha_primer_entrenamiento date,
  lugar_primer_entrenamiento character varying,
  fecha_segundo_entrenamiento date,
  lugar_segundo_entrenamiento character varying,
  login character varying,
  usuario_registra character varying,
  fecha_registro date,
  usuario_modifica character varying,
  fecha_modificacion date,
  mensaje_primer_entrenamiento date,
  mensaje_segundo_entrenamiento date,
  entrenamiento_requerido character varying,
  fecha_aprobacion date,
  apellido_casada character varying,
  fecha_primera_capacitacion date,
  lugar_primera_capacitacion integer,
  fecha_segunda_capacitacion date,
  lugar_segunda_capacitacion integer,
  fecha_cumple_requisitos date,
  existe_bd_anterior character varying,
  asistio_primera_capacitacion character varying not null default 'NO'::character varying,
  asistio_segunda_capacitacion character varying not null default 'NO'::character varying,
  fecha_actualizacion_datos date,
  usuario_actualiza_datos character varying,
  justificacion text not null,
  fecha_retiro date,
  usuario_retira character varying,
  estado_solicitud_retiro character varying
);

alter table public.publicadores_retirados enable row level security;
